Document: mplex
Title: Debian mplex Manual
Author: <insert document author here>
Abstract: This manual describes what mplex is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mplex/mplex.sgml.gz

Format: postscript
Files: /usr/share/doc/mplex/mplex.ps.gz

Format: text
Files: /usr/share/doc/mplex/mplex.text.gz

Format: HTML
Index: /usr/share/doc/mplex/html/index.html
Files: /usr/share/doc/mplex/html/*.html
